### PR TITLE
Bypass cmocka memory allocation check

### PR DESCRIPTION
**Pull request by vlvkobal**
It's a quick and dirty fix. I tried to mend cmocka memory allocation checks in a more correct way, but it turned out that such an approach would need a lot of changes and take quite a lot of time 😞.

### CODE REVIEW

**Comment by ktsaou** [comment]
I think a better way could be to `#define strdupz(x) strdup(x)` at the beginning. We may have more allocations in the future.

**Comment by ktsaou** [comment]
You have this problem only with `rrdlabels`? Dictionaries for example do not need this?

**Comment by vlvkobal** [comment]
> You have this problem only with rrdlabels? Dictionaries for example do not need this?

Right now it's only `rrdlabel_delete_callback()`. I don't know for sure if the dictionaries are used in any other place in the exporting tests. I couldn't find why cmocka uses sometimes libc allocation functions instead of its own `test_*` variants.

**Comment by vlvkobal** [comment]
The correct approach is to make cmocka use only its own allocation functions. But it's difficult to mend the tests because cmocka provides very poor debug information about memory allocation. A lot of guess and try iterations are needed to fix an allocation error.

**Pull request merged**
